// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjotqkgbuykzzcmxepez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb3Rxa2didXlrenpjbXhlcGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTk1NzYsImV4cCI6MjA3MzkzNTU3Nn0.-79X9vwJmQJtgfCiOtm92xMlQPT0kiBASelvYVNj-bY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});